=== anonymous-000000/DeepEx/PA-tool/database/config.dtd
<!ELEMENT methods (method)+>
<!ELEMENT method (id, exceptions, params, arity)>
<!ATTLIST method name CDATA #REQUIRED>
<!ELEMENT id (#PCDATA)>
<!ELEMENT exceptions (e)+>
<!ELEMENT e (#PCDATA)>
<!ELEMENT params (param)*>
<!ELEMENT param (type, name)*>
<!ELEMENT arity (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT name (#PCDATA)>

=== anonymous-000000/DeepEx/PA-tool/database/xstream.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE methods SYSTEM "config.dtd">
<methods>
  <method name="addImmutableType">
    <id>com.thoughtworks.xstream.XStream.addImmutableType( Class )</id>
    <exceptions>
      <e>InitializationException</e>
    </exceptions>
    <params>
      <param>
        <type>Class</type>
        <name>type</name>
      </param>
    </params>
    <arity>1</arity>
  </method>
  <method name="createObjectInputStream">
    <id>com.thoughtworks.xstream.XStream.createObjectInputStream( InputStream )</id>
    <exceptions>
      <e>IOException</e>
    </exceptions>
    <params>
      <param>
        <type>InputStream</type>
        <name>in</name>
      </param>
    </params>
    <arity>1</arity>
  </method>
  <method name="XStream">
    <id>com.thoughtworks.xstream.XStream.XStream( HierarchicalStreamDriver )</id>
    <exceptions>
      <e>InitializationException</e>
    </exceptions>
    <params>
      <param>
        <type>HierarchicalStreamDriver</type>
        <name>hierarchicalStreamDriver</name>
      </param>
    </params>
    <arity>1</arity>
  </method>
  <method name="CustomObjectInputStream">
    <id>com.thoughtworks.xstream.core.util.CustomObjectInputStream.CustomObjectInputStream( StreamCallback ClassLoader )</id>
    <exceptions>
      <e>SecurityException</e>
      <e>IOException</e>
    </exceptions>
    <params>
      <param>
        <type>StreamCallback</type>
        <name>callback</name>
      </param>
      <param>
        <type>ClassLoader</type>
        <name>classLoader</name>
      </param>
    </params>
    <arity>2</arity>
  </method>
  <method name="createObjectOutputStream">
    <id>com.thoughtworks.xstream.io.xml.TraxSource.createObjectOutputStream( Templates Writer String )</id>
    <exceptions>
      <e>IOException</e>
    </exceptions>
    <params>
      <param>
        <type>Templates</type>
        <name>stylesheet</name>
      </param>
      <param>
        <type>Writer</type>
        <name>writer</name>
      </param>
      <param>
        <type>String</type>
        <name>rootNodeName</name>
      </param>
    </params>
    <arity>3</arity>
  </method>
  <method name="StaxWriter">
    <id>com.thoughtworks.xstream.io.xml.StaxWriter.StaxWriter( QNameMap XMLStreamWriter boolean boolean XmlFriendlyReplacer )</id>
    <exceptions>
      <e>XMLStreamException</e>
    </exceptions>
    <params>
      <param>
        <type>QNameMap</type>
        <name>qnameMap</name>
      </param>
      <param>
        <type>XMLStreamWriter</type>
        <name>out</name>
      </param>
      <param>
        <type>boolean</type>
        <name>writeEnclosingDocument</name>
      </param>
      <param>
        <type>boolean</type>
        <name>namespaceRepairingMode</name>
      </param>
      <param>
        <type>XmlFriendlyReplacer</type>
        <name>replacer</name>
      </param>
    </params>
    <arity>5</arity>
  </method>
  <method name="readObject">
    <id>com.thoughtworks.xstream.mapper.PackageAliasingMapper.readObject( ObjectInputStream )</id>
    <exceptions>
      <e>IOException</e>
      <e>ClassNotFoundException</e>
    </exceptions>
    <params>
      <param>
        <type>ObjectInputStream</type>
        <name>in</name>
      </param>
    </params>
    <arity>1</arity>
  </method>
  <method name="createReader">
    <id>com.thoughtworks.xstream.io.xml.Dom4JDriver.createReader( )</id>
    <exceptions>
      <e>DocumentException</e>
    </exceptions>
    <params/>
    <arity>0</arity>
  </method>
  <method name="XmlHeaderAwareReader">
    <id>com.thoughtworks.xstream.core.util.XmlHeaderAwareReader.XmlHeaderAwareReader( InputStream )</id>
    <exceptions>
      <e>UnsupportedEncodingException</e>
      <e>IOException</e>
    </exceptions>
    <params>
      <param>
        <type>InputStream</type>
        <name>in</name>
      </param>
    </params>
    <arity>1</arity>
  </method>
  <method name="writeObject">
    <id>com.thoughtworks.xstream.mapper.AnnotationMapper.writeObject( ObjectOutputStream )</id>
    <exceptions>
      <e>IOException</e>
    </exceptions>
    <params>
      <param>
        <type>ObjectOutputStream</type>
        <name>out</name>
      </param>
    </params>
    <arity>1</arity>
  </method>
  <method name="writeByte">
    <id>com.thoughtworks.xstream.core.util.CustomObjectOutputStream.writeByte( int )</id>
    <exceptions>
      <e>IOException</e>
    </exceptions>
    <params>
      <param>
        <type>int</type>
        <name>val</name>
      </param>
    </params>
    <arity>1</arity>
  </method>
  <method name="createObjectOutputStream">
    <id>com.thoughtworks.xstream.io.xml.TraxSource.createObjectOutputStream( Source OutputStream String )</id>
    <exceptions>
      <e>TransformerConfigurationException</e>
      <e>IOException</e>
    </exceptions>
    <params>
      <param>
        <type>Source</type>
        <name>stylesheet</name>
      </param>
      <param>
        <type>OutputStream</type>
        <name>target</name>
      </param>
      <param>
        <type>String</type>
        <name>rootNodeName</name>
      </param>
    </params>
    <arity>3</arity>
  </method>
  <method name="field">
    <id>com.thoughtworks.xstream.converters.reflection.FieldDictionary.field( Class String Class )</id>
    <exceptions>
      <e>ObjectAccessException</e>
    </exceptions>
    <params>
      <param>
        <type>Class</type>
        <name>cls</name>
      </param>
      <param>
        <type>String</type>
        <name>name</name>
      </param>
      <param>
        <type>Class</type>
        <name>definedIn</name>
      </param>
    </params>
    <arity>3</arity>
  </method>
  <method name="fromXML">
    <id>com.thoughtworks.xstream.XStreamer.fromXML( Reader )</id>
    <exceptions>
      <e>XStreamException</e>
      <e>IOException</e>
      <e>ClassNotFoundException</e>
    </exceptions>
    <params>
      <param>
        <type>Reader</type>
        <name>xml</name>
      </param>
    </params>
    <arity>1</arity>
  </method>
  <method name="JettisonStaxWriter">
    <id>com.thoughtworks.xstream.io.json.JettisonStaxWriter.JettisonStaxWriter( QNameMap XMLStreamWriter boolean boolean NameCoder MappedNamespaceConvention )</id>
    <exceptions>
      <e>XMLStreamException</e>
    </exceptions>
    <params>
      <param>
        <type>QNameMap</type>
        <name>qnameMap</name>
      </param>
      <param>
        <type>XMLStreamWriter</type>
        <name>out</name>
      </param>
      <param>
        <type>boolean</type>
        <name>writeEnclosingDocument</name>
      </param>
      <param>
        <type>boolean</type>
        <name>namespaceRepairingMode</name>
      </param>
      <param>
        <type>NameCoder</type>
        <name>nameCoder</name>
      </param>
      <param>
        <type>MappedNamespaceConvention</type>
        <name>convention</name>
      </param>
    </params>
    <arity>6</arity>
  </method>
  <method name="addDefaultImplementation">
    <id>com.thoughtworks.xstream.XStream.addDefaultImplementation( Class Class )</id>
    <exceptions>
      <e>InitializationException</e>
    </exceptions>
    <params>
      <param>
        <type>Class</type>
        <name>defaultImplementation</name>
      </param>
      <param>
        <type>Class</type>
        <name>ofType</name>
      </param>
    </params>
    <arity>2</arity>
  </method>
  <method name="fromXML">
    <id>com.thoughtworks.xstream.XStream.fromXML( String T )</id>
    <exceptions>
      <e>XStreamException</e>
    </exceptions>
    <params>
      <param>
        <type>String</type>
        <name>xml</name>
      </param>
      <param>
        <type>T</type>
        <name>root</name>
      </param>
    </params>
    <arity>2</arity>
  </method>
  <method name="setXMLReader">
    <id>com.thoughtworks.xstream.io.xml.TraxSource.setXMLReader( XMLReader )</id>
    <exceptions>
      <e>UnsupportedOperationException</e>
    </exceptions>
    <params>
      <param>
        <type>XMLReader</type>
        <name>reader</name>
      </param>
    </params>
    <arity>1</arity>
  </method>
  <method name="fromXML">
    <id>com.thoughtworks.xstream.XStream.fromXML( URL )</id>
    <exceptions>
      <e>XStreamException</e>
    </exceptions>
    <params>
      <param>
        <type>URL</type>
        <name>url</name>
      </param>
    </params>
    <arity>1</arity>
  </method>
  <method name="JettisonStaxWriter">
    <id>com.thoughtworks.xstream.io.json.JettisonStaxWriter.JettisonStaxWriter( QNameMap XMLStreamWriter NameCoder MappedNamespaceConvention )</id>
    <exceptions>
      <e>XMLStreamException</e>
    </exceptions>
    <params>
      <param>
        <type>QNameMap</type>
        <name>qnameMap</name>
      </param>
      <param>
        <type>XMLStreamWriter</type>
        <name>out</name>
      </param>
      <param>
        <type>NameCoder</type>
        <name>nameCoder</name>
      </param>
      <param>
        <type>MappedNamespaceConvention</type>
        <name>convention</name>
      </param>
    </params>
    <arity>4</arity>
  </method>
  <method name="writeFloat">
    <id>com.thoughtworks.xstream.core.util.CustomObjectOutputStream.writeFloat( float )</id>
    <exceptions>
      <e>IOException</e>
    </exceptions>
    <params>
      <param>
        <type>float</type>
        <name>val</name>
      </param>
    </params>
    <arity>1</arity>
  </method>
  <method name="flush">
    <id>com.thoughtworks.xstream.core.util.CustomObjectOutputStream.flush( )</id>
    <exceptions>
      <e>IOException</e>
    </exceptions>
    <params/>
    <arity>0</arity>
  </method>
  <method name="useAttributeFor">
    <id>com.thoughtworks.xstream.XStream.useAttributeFor( Class )</id>
    <exceptions>
      <e>InitializationException</e>
    </exceptions>
    <params>
      <param>
        <type>Class</type>
        <name>type</name>
      </param>
    </params>
    <arity>1</arity>
  </method>
  <method name="readFrom">
